apiVersion: v1
kind: Service
metadata:
  name: test-load
spec:
  ports:
    - port: 8080 # Port the service listens on
      targetPort: 80 # Port the traffic is sent to in the pod
  selector:
    app: test-deploy-manifest
  type: LoadBalancer